### ISSUE TITLE
Wrong poker hand evaluation

### ISSUE THREAD

**Issue by sidsaxena0** [thlorenz/phe#3]
Hi , i am trying to use your library in my project but i am getting a very weird error, as sometimes it returns wrong result and wrong description of hand. My cards are : **2d 6s 6c 3d 10c** it returns rank **6** and description is a Two Pair which is incorrect as it is  **One Pair**.

My code snippet is below : 

`  const rank = rankBoard(board);
        const name = rankDescription[rank];
// where board is a string containing 2d 6s 6c 3d 10c
`

Please help with it, if i am doing something wrong.

**Comment by HenryRLee** [comment]
Hi, thanks for submitting an issue. I think the fifth input should be `Tc` instead of `10c`.

```javascript
> const board = '2d 6s 6c 3d Tc';
> rankDescription[rankBoard(board)]
'One Pair'
```

**Comment by HenryRLee** [comment]
Hi, thanks for submitting an issue. I think the fifth input should be `Tc` instead of `10c`.

```javascript
> const board = '2d 6s 6c 3d Tc';
> rankDescription[rankBoard(board)]
'One Pair'
```

**Comment by elieobeid7** [comment]
This issue should be closed

**Comment by sidsaxena0** [comment]
OK sure, closing now as i was passing wrong card name for **10**
