### ISSUE TITLE
handRank does not return royal flush

### ISSUE THREAD

**Issue by elieobeid7** [thlorenz/phe#4]
I copy-paste from the readme 

Converts a hand strength number into a hand rank number 0 - 8 for STRAIGHT_FLUSH - HIGH_CARD.

What about royal flush? there should be 0-9 ranks

Nowhere in the code, I see anything related to royal, maybe this library doesn't support royal flush, strange

**Comment by elieobeid7** [comment]
According to 

https://github.com/HenryRLee/PokerHandEvaluator/blob/35c8f8d1331f446c5811e50ebdcc4add94d5c705/README.md

> The return value is identical to the Cactus Kev's evaluator. The strongest hands (Royal straight flush) are returned with 1, and the second strongest hands (King high straight flush) are returned with 2 and so on. The weakest hands have the return value 7462.


I don't know if this library returns one for royal, I hope so, otherwise, I'd have to write my own poker evaluator.

**Comment by HenryRLee** [comment]
I think currently there is no rank description called Royal Straight Flush in this library.

You don't have to write your own evaluator from scratch. To have Royal Straight Flush, it is easy to write your own helper method, as the Royal Straight Flush are the hands with hand value equals to 1:

```
const myHandRank = (val) => {
  if (val == 1) return 0;
  else return handRank(val) + 1;
};
```

Then 0 indicates Royal Straight Flush, and the rest of them are shifted to 1 - 9.

**Comment by elieobeid7** [comment]
Thank you so much.
